import { ApiClassParser } from './ApiClassParser';

export function init(app: any) {
  const parser = Parser.getInstance()
  app.addHook('parser-find-elements', (...args: any[]) => parser.parseElements.apply(parser, args), 200)
}

class Parser {
  private static instance: Parser;
  private map: any;

  constructor() {
    // Supported types now
    const types = [
      'apiParamClass',
      'apiSuccessClass'
    ]
    this.map = {}
    for (const type of types) {
      this.map[type.toLowerCase()] = type
    }
  }

  static getInstance() {
    return this.instance || (this.instance = new Parser())
  }

  /**
   * Plugin parse entry function
   *
   * @param elements All elements generated by apidoc
   * @param element this element
   * @param _block
   * @param _filename
   */
  parseElements(elements: any[], element: any, _block: any, _filename: any) {
    if (!this.map[element.name]) {
      return
    }
    // Use Api Class Parser to parse class definition
    const instance = new ApiClassParser(this.map[element.name])
    instance.parseElements(elements, element)
  }
}
